name: Build & Push Docker Image

on: push

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]
        type: [ 'cli' ]

    name: Build Docker Image for PHP ${{ matrix.php }} and Type ${{ matrix.type }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.php }}/
          file: ./${{ matrix.php}}/${{ matrix.type }}.Dockerfile
          push: true
          tags: elyday/laravel-docker:${{ matrix.php }}-${{ matrix.type }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
